---
title: "Italian public debt growth"
author: "Massimiliano Figini"
date: "March 2, 2017"
output: 
  html_document: 
    keep_md: yes
---

This map shows the results of the last Italian constitutional referendum (4 December 2016) in the municipality of my province, Monza and Brianza (Lombardy).  


**Data Information**  
Each record is a municipality of the province.The columns are:  
*denominazione*: name.  
*latitudine*: latitude.  
*longitudine*: longitude.  
*ELETTORI*: potential voters for the referendum.  
*VOTANTI*: voters for the referendum.  
*NUMVOTISI*: number of YES voters.  
*NUMVOTINO*: number of NO voters.

**Map design**  
*Circles colors*: red for the municipality where NO won (over 50% of valid vote was NO), green where YES won.  
*Circles dimension*: proportional to the number of voters.  
*Circles opacity*: based on election turnout (voters percentage).  
*Circles label*: name of municipality (when step on it).  
*Circles popup*: results of referendum for the municipality (when click on it) 

</br>

```{r code, echo=TRUE}
# import package
library(plotly)
# getting and cleaning data
DP <- read.csv2("C:/Users/figinim/Documents/Studies/Developing Data Products/Course Project 2/Debito-PIL_Italia.csv")
# create the graph
plot_ly(DP, x = ~Anno, y = ~Debito, type = "scatter", size = ~PIL,hoverinfo = "text", text = ~paste("Year:",Anno,"</br>Debt:",Debito,"</br>GDP:",PIL,"</br>Debt-to-GDP:",round(Debito/PIL*100),4)) %>%layout(title = "Italian public debt growth",xaxis = list(title = "Year"),yaxis = list(title = "Public debt in euros"))
```